config/routes.rb
Freshdesktool::Application.routes.draw do
  devise_for :users  
  root :to => "projects#index"

       devise_scope :user do
        get "users/sign_out",:to=>"devise/sessions#destroy", :as => "signout"
      end

resources :cases
resources :groups
resources :customers do
  member do
    get 'get_users'
  end
end
resources :projects
resources :notes
resources :replies
resources :attachments
resources :companies
resources :facebook_users
resources :twitter_users

end

app/models/project.rb
class Project < ActiveRecord::Base
	belongs_to :user
	scope :get_project, lambda {|p_id| where("id = ?", p_id)  }
	validates :name, :presence => {:message => "Please enter Project name"}
    validates :support_email, :presence => {:message => "Please enter Support Eemail"}
    validates :subdomain, :presence => {:message => "Please enter Subdomain"}
    validates :consumer_key, :presence => {:message => "Please enter Consumer key"}
    validates :consumer_secret, :presence => {:message => "Please enter Consumer Secret"}
    validates :oauth_token, :presence => {:message => "Please enter Oauth Token"}
    validates :oauth_token_secret, :presence => {:message => "Please enter Oauth Token Secret"}
    has_one :project_file
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
	before_filter :authenticate_user!
	layout 'project'
	#This method used for get the projects
	def index
		@user_projects = current_user.projects
	end
	def new
	end
	#This method used for create a new project
	def create
	 project=current_user.projects.new(params[:project])
	 if project.save
	    redirect_to projects_path
	 else
      @errors = project.errors
	  	render :new
	 end
	end
   #This method used for edit the project details
   def edit
   	@project = Project.find(params[:id])
   end
   #This method used for display a project detail
   def show
   	@project = Project.find(params[:id])
   end
   #This method used for update the project detail
   def update
   	 @project = Project.find(params[:id])
   	 if @project.update_attributes(params[:project])
   	 	redirect_to projects_path
   	 else
         @errors = @project.errors
   	 	render :edit
   	 end
   end
   #This method used for delete a project record
   def destroy
   	 project = Project.find(params[:id])
   	 project.destroy
   	 redirect_to projects_path
   end

end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/edit.html.erb
<div class="row">
  <div class="col-sm-6">
    <section class="panel panel-default">
      <header class="panel-heading">Create Project</header>
      <div class="panel-body">
        <%=form_tag(project_path(@project),:method => :put) do %>
          <div class="form-group">
            <label>Name</label>
            <input type="text" value="<%=@project.name%>" class="form-control" name="project[name]">
            <div style="color:red;"><%=@errors[:name][0] if !@errors.nil? && !@errors[:name].nil?%></div>
          </div>
          <div class="form-group">
            <label>Support Email</label>
            <input type="text" value="<%=@project.support_email%>" class="form-control" name="project[support_email]">
            <div style="color:red;"><%=@errors[:support_email][0] if !@errors.nil? && !@errors[:support_email].nil?%></div>
          </div>
          <div class="form-group">
            <label>Sub Domain</label>
            <input type="text"  value="<%=@project.subdomain%>" class="form-control" name="project[subdomain]">
            <div style="color:red;"><%=@errors[:subdomain][0] if !@errors.nil? && !@errors[:subdomain].nil?%></div>
          </div>
          <div class="form-group">
            <label>Consumer Key</label>
            <input type="text"  value="<%=@project.consumer_key%>" class="form-control" name="project[consumer_key]">
            <div style="color:red;"><%=@errors[:consumer_key][0] if !@errors.nil? && !@errors[:consumer_key].nil?%></div>
          </div>
          <div class="form-group">
            <label>Consumer Secret</label>
            <input type="text"  value="<%=@project.consumer_secret%>" class="form-control" name="project[consumer_secret]">
            <div style="color:red;"><%=@errors[:consumer_secret][0] if !@errors.nil? && !@errors[:consumer_secret].nil?%></div>
          </div>
          <div class="form-group">
            <label>Oauth Token</label>
            <input type="text"  value="<%=@project.oauth_token%>" class="form-control" name="project[oauth_token]">
            <div style="color:red;"><%=@errors[:oauth_token][0] if !@errors.nil? && !@errors[:oauth_token].nil?%></div>
          </div>
          <div class="form-group">
            <label>Oauth Token Secret</label>
            <input type="text"  value="<%=@project.oauth_token_secret%>" class="form-control" name="project[oauth_token_secret]">
            <div style="color:red;"><%=@errors[:oauth_token_secret][0] if !@errors.nil? && !@errors[:oauth_token_secret].nil?%></div>
          </div>                     
          
          <button type="submit" class="btn btn-sm btn-default">Edit</button>
        <%end%>
      </div>
    </section>
  </div>

app/views/projects/index.html.erb
<div class="table-responsive">
<table class="table table-striped b-t b-light text-sm">
  <thead>
    <tr>
      <th class="th-sortable" data-toggle="class">Project <span class="th-sort"> <i class="fa fa-sort-down text"></i> <i class="fa fa-sort-up text-active"></i> <i class="fa fa-sort"></i> </span> </th>
      <th>Task</th>
      <th width="30"></th>
      <th>Action</th>
    </tr>
  </thead>
  <tbody>
  	<%unless @user_projects.nil? %>
  	  <% @user_projects.each do |project|%>
    <tr>
      <td><%=link_to "#{project.name}", project_path(project) %></td>
      <td><%=project.created_at.strftime("%d/%m/%Y")%></td>
      <td><%=link_to "Edit", edit_project_path(project) %></td>
      <td><%=link_to "Delete", project_path(project), :confirm => "Are you sure", :method => :delete %></td>
    </tr>
    <%end%>
    <%end%>
  </tbody>
</table>
</div>

app/views/projects/new.html.erb
<div class="row">
  <div class="col-sm-6">
    <section class="panel panel-default">
      <header class="panel-heading">Create Project</header>
      <div class="panel-body">
        <%=form_tag(projects_path) do %>
          <div class="form-group">
            <label>Name</label>
            <input type="text" placeholder="Name" class="form-control" name="project[name]">
            <div style="color:red;"><%=@errors[:name][0] if !@errors.nil? && !@errors[:name].nil?%></div>
          </div>
          <div class="form-group">
            <label>Support Email</label>
            <input type="text" placeholder="Support Email" class="form-control" name="project[support_email]">
            <div style="color:red;"><%=@errors[:support_email][0] if !@errors.nil? && !@errors[:support_email].nil?%></div>
          </div>
          <div class="form-group">
            <label>Sub Domain</label>
            <input type="text"  placeholder="Sub Domain" class="form-control" name="project[subdomain]">
            <div style="color:red;"><%=@errors[:subdomain][0] if !@errors.nil? && !@errors[:subdomain].nil?%></div>
          </div>
          <div class="form-group">
            <label>Consumer Key</label>
            <input type="text"  placeholder="Consumer Key" class="form-control" name="project[consumer_key]">
            <div style="color:red;"><%=@errors[:consumer_key][0] if !@errors.nil? && !@errors[:consumer_key].nil?%></div>
          </div>
          <div class="form-group">
            <label>Consumer Secret</label>
            <input type="text"  placeholder="Consumer Secret" class="form-control" name="project[consumer_secret]">
            <div style="color:red;"><%=@errors[:consumer_secret][0] if !@errors.nil? && !@errors[:consumer_secret].nil?%></div>
          </div>
          <div class="form-group">
            <label>Oauth Token</label>
            <input type="text"  placeholder="Oauth Token" class="form-control" name="project[oauth_token]">
            <div style="color:red;"><%=@errors[:oauth_token][0] if !@errors.nil? && !@errors[:oauth_token].nil?%></div>
          </div>
          <div class="form-group">
            <label>Oauth Token Secret</label>
            <input type="text"  placeholder="Oauth Token Secret" class="form-control" name="project[oauth_token_secret]">
            <div style="color:red;"><%=@errors[:oauth_token_secret][0] if !@errors.nil? && !@errors[:oauth_token_secret].nil?%></div>
          </div>                     
          
          <button type="submit" class="btn btn-sm btn-default">Create</button>
        <%end%>
      </div>
    </section>
  </div>

app/views/projects/show.html.erb
<%#=link_to 'Get Users', get_users_customer_path(@project.id),:class=>"btn btn-sm btn-default"  %>

<%=link_to 'Get Users', "#",:class=>"btn btn-sm btn-default", :onclick => "show_statusbar(#{@project.id},'customers/get_users')"  %>

<%=link_to 'Get Cases', "#",:class=>"btn btn-sm btn-default", :onclick => "show_statusbar(#{@project.id},'cases')" %>

<%=link_to 'Get Customers', "#",:class=>"btn btn-sm btn-default", :onclick => "show_statusbar(#{@project.id},'customers')"  %>

<%#=link_to 'Get Groups', groups_path(:project_id=>"#{@project.id}"),:class=>"btn btn-sm btn-default", :onclick => "show_statusbar()" %>
<%=link_to 'Get Groups', "#",:class=>"btn btn-sm btn-default", :onclick => "show_statusbar(#{@project.id},'groups')" %>
<%=link_to 'Get Notes', "#",:class=>"btn btn-sm btn-default", :onclick => "show_statusbar(#{@project.id},'notes')"  %>

<%=link_to 'Get Replies', "#",:class=>"btn btn-sm btn-default", :onclick => "show_statusbar(#{@project.id},'replies')"%>

<%=link_to 'Get Attachments', "#",:class=>"btn btn-sm btn-default", :onclick => "show_statusbar(#{@project.id},'attachments')"%>

<%=link_to 'Get Companies', "#",:class=>"btn btn-sm btn-default", :onclick => "show_statusbar(#{@project.id},'companies')"%>

<%=link_to 'Get Facebook Users', "#",:class=>"btn btn-sm btn-default", :onclick => "show_statusbar(#{@project.id},'facebook_users')"%>

<%=link_to 'Get Twitter Users', "#",:class=>"btn btn-sm btn-default", :onclick => "show_statusbar(#{@project.id},'twitter_users')"%>
<div class="loadbar" style="display:none;">
	<%=image_tag("loading.gif")%>
	</div>
<div class="download"></div>
<div class="error"></div>
<br>

 <!--For CSV list box-->
<% if @project.project_file %>
<div class="row">       
    <div class="col-lg-2-4">
        <section class="panel panel-default CSVBox"> 
            <div class="panel-body">
          <!-- User csv -->
            <h4>User</h4>
            <h6>Last Downloaded at <%=@project.project_file.user_download_at%></h6>
            <section class="scrollable CSVList">
              <ul>
                <%unless @project.project_file.csv_user.nil? %>
                <% count = 0 %>
                <% @project.project_file.csv_user.split(',').each do | user_link| %>
                <li><%=link_to "#{user_link.split('/').last}", customer_path(@project.id,:get_user => true,:fetch =>count)%></li>
                <% count = count +1 %>
                <%end%>
                <%end%>
                </ul>
            </section>
            </div>
        </section> 
    </div>
     <!--Customer  csv -->
    <div class="col-lg-2-4">
        <section class="panel panel-default CSVBox"> 
            <div class="panel-body">
            <h4>Customer</h4>
            <h6>Last Downloaded at <%=@project.project_file.customer_download_at%></h6>
            <section class="scrollable CSVList">
              <ul>
                <%unless @project.project_file.csv_customer.nil? %>
                 <% count = 0 %>
              <% @project.project_file.csv_customer.split(',').each do | user_link| %>
              <li><%=link_to "#{user_link.split('/').last}", customer_path(@project.id,:fetch =>count)%></li>
              <% count = count +1 %>
              <%end%>
              <%end%>
                </ul>
            </section>
            </div>
        </section> 
    </div>
    
    <div class="col-lg-2-4">
        <section class="panel panel-default CSVBox"> 
            <div class="panel-body">
            <h4>Case</h4>
            <h6>Last Downloaded at <%=@project.project_file.case_download_at%></h6>
            <section class="scrollable CSVList">
              <ul>
                <%unless @project.project_file.csv_case.nil? %>
                 <% count = 0 %>
            <% @project.project_file.csv_case.split(',').each do | user_link| %>
            <li><%=link_to "#{user_link.split('/').last}", case_path(@project.id,:fetch =>count)%></li>
            <% count = count +1 %>
            <%end%>
            <%end%>
                </ul>
            </section>
            </div>
        </section> 
    </div>
    
    <div class="col-lg-2-4">
        <section class="panel panel-default CSVBox"> 
            <div class="panel-body">
            <h4>Company</h4>
            <h6>Last Downloaded at <%=@project.project_file.company_download_at%></h6>
            <section class="scrollable CSVList">
              <ul>
                  <%unless @project.project_file.csv_company.nil? %>
                 <% count = 0 %>
                <% @project.project_file.csv_company.split(',').each do | user_link| %>
                <li><%=link_to "#{user_link.split('/').last}", company_path(@project.id,:fetch =>count)%></li>
                <% count = count +1 %>
                 <%end%>
                <%end%>
                </ul>
            </section>
            </div>
        </section> 
    </div>
    
    <div class="col-lg-2-4">
        <section class="panel panel-default CSVBox"> 
            <div class="panel-body">
            <h4>Group</h4>
            <h6>Last Downloaded at <%=@project.project_file.group_download_at%></h6>
            <section class="scrollable CSVList">
              <ul>
                   <%unless @project.project_file.csv_group.nil? %>
                  <% count = 0 %>
                <% @project.project_file.csv_group.split(',').each do | user_link| %>
                <li><%=link_to "#{user_link.split('/').last}", group_path(@project.id,:fetch =>count)%></li>
                <% count = count +1 %>
                 <%end%>
                <%end%>
                </ul>
            </section>
            </div>
        </section> 
    </div>
            
<div class="col-lg-2-4">
<section class="panel panel-default CSVBox"> 
    <div class="panel-body">
    <h4>Note</h4>
    <h6>Last Downloaded at <%=@project.project_file.note_download_at%></h6>
    <section class="scrollable CSVList">
      <ul>
            <%unless @project.project_file.csv_note.nil? %>
              <% count = 0 %>
            <% @project.project_file.csv_note.split(',').each do | user_link| %>
            <li><%=link_to "#{user_link.split('/').last}", note_path(@project.id,:fetch =>count)%></li>
            <% count = count +1 %>
             <%end%>
            <%end%>
        </ul>
    </section>
    </div>
</section> 
</div>

<div class="col-lg-2-4">
<section class="panel panel-default CSVBox"> 
    <div class="panel-body">
    <h4>Reply</h4>
    <h6>Last Downloaded at 15:00, 28 Jan 2014</h6>
    <section class="scrollable CSVList">
      <ul>
        <%unless @project.project_file.csv_reply.nil? %>
         <% count = 0 %>
        <% @project.project_file.csv_reply.split(',').each do | reply_link| %>
        <li><%=link_to "#{reply_link.split('/').last}", reply_path(@project.id,:fetch =>count)%></li>
        <% count = count +1 %>
         <%end%>
        <%end%>
        </ul>
    </section>
    </div>
</section> 
</div>

<div class="col-lg-2-4">
<section class="panel panel-default CSVBox"> 
    <div class="panel-body">
    <h4>Attachment</h4>
    <h6>Last Downloaded at <%=@project.project_file.attachment_download_at%></h6>
    <section class="scrollable CSVList">
      <ul>
         <%unless @project.project_file.csv_attachment.nil? %>
          <% count = 0 %>
        <% @project.project_file.csv_attachment.split(',').each do | attachment_link| %>
        <li><%=link_to "#{attachment_link.split('/').last}", attachment_path(@project.id,:fetch =>count)%></li>
        <% count = count +1 %>
         <%end%>
        <%end%>
        </ul>
    </section>
    </div>
</section> 
</div>

<div class="col-lg-2-4">
<section class="panel panel-default CSVBox"> 
    <div class="panel-body">
    <h4>Facebook User</h4>
    <h6>Last Downloaded at <%=@project.project_file.facebook_user_download_at%></h6>
    <section class="scrollable CSVList">
      <ul>
    <%unless @project.project_file.csv_facebook.nil? %>
    <% count = 0 %>
    <% @project.project_file.csv_facebook.split(',').each do | user_link| %>
    <li><%=link_to "#{user_link.split('/').last}", facebook_user_path(@project.id,:fetch =>count)%></li>
    <% count = count +1 %>
     <%end%>
    <%end%>
        </ul>
    </section>
    </div>
</section> 
</div>

<div class="col-lg-2-4">
<section class="panel panel-default CSVBox"> 
    <div class="panel-body">
    <h4>Twitter User</h4>
    <h6>Last Downloaded at <%=@project.project_file.twitter_user_download_at%></h6>
    <section class="scrollable CSVList">
      <ul>
        <%unless @project.project_file.csv_twitter.nil? %>
         <% count = 0 %>
        <% @project.project_file.csv_twitter.split(',').each do | twitter_link| %>
        <li><%=link_to "#{twitter_link.split('/').last}", twitter_user_path(@project.id,:fetch =>count)%></li>
        <% count = count +1 %>
         <%end%>
        <%end%>
        </ul>
    </section>
    </div>
</section> 
</div>   
<%end%> 