config/routes.rb
Freshdesktool::Application.routes.draw do
  devise_for :users  
  root :to => "projects#index"

       devise_scope :user do
        get "users/sign_out",:to=>"devise/sessions#destroy", :as => "signout"
      end

resources :cases
resources :groups
resources :customers do
  member do
    get 'get_users'
  end
end
resources :projects
resources :notes
resources :replies
resources :attachments
resources :companies
resources :facebook_users
resources :twitter_users

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en" class="bg-dark loginSignupBg">
<head>
<meta charset="utf-8" />
<title>Export Tool</title>
<meta name="description" content="app, web app, responsive, admin dashboard, admin, flat, flat ui, ui kit, off screen nav" />
<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1" />
 <%= stylesheet_link_tag "application" %></head>
<body>
<section id="content" class="m-t-lg wrapper-md animated fadeInUp">
  <div class="container aside-xxl"><a class="navbar-brand block" href="<%=url_for root_path%>">Export Tool</a>
    <section class="panel panel-default bg-white m-t-lg">
      <header class="panel-heading text-center"> <strong>
      <%if params[:controller]=='devise/sessions' %>
        Log In
        <%elsif params[:controller]=='devise/registrations' %>
         Registration
         <%elsif params[:controller]=='devise/passwords' %>
         Reset Password
         <%end%>
      </strong> 
    </header>
<%=yield%>
       <div class="wrapper-lg">
        <%if params[:controller]=='devise/sessions' %>  
        <!--<a href="#" class="btn btn-facebook btn-block m-b-sm"><i class="fa fa-facebook pull-left"></i>Sign in with Facebook</a> <a href="#" class="btn btn-twitter btn-block"><i class="fa fa-twitter pull-left"></i>Sign in with Twitter</a>-->
          <p class="text-muted text-center"><small>Do not have an account?</small></p>
          <a href="<%=url_for new_user_registration_path%>" class="btn btn-default btn-block">Create an account</a>
        <%end%>
        <%if params[:controller]=='devise/registrations' || params[:controller]=='devise/passwords' %>
          <p class="text-muted text-center"><small>Already have an account?</small></p>
          <a href="<%=url_for new_user_session_path%>" class="btn btn-default btn-block">Log In</a>
        <%end%>
         </div>
    </section>
  </div>
</section>
<!-- footer -->
<footer id="footer">
  <div class="text-center padder">
    <p>&copy; <%=Date.today.year%> All rights reserved Freshdesk  </small> </p>
  </div>
</footer>
<!-- / footer --> <script src="js/application.js"></script> <!-- Bootstrap --> <!-- App -->
</body>
</html>

app/views/layouts/project.html.erb
<!DOCTYPE html>
<html lang="en" class="app">
<head>
<meta charset="utf-8" />
<title>Export Tool</title>
<meta name="description" content="app, web app, responsive, admin dashboard, admin, flat, flat ui, ui kit, off screen nav" />
<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1" />
  <%= stylesheet_link_tag "application" %>
</head>
<body>
<section class="vbox">
  <header class="bg-dark dk header navbar navbar-fixed-top-xs">
    <div class="navbar-header aside-md"> <a class="btn btn-link visible-xs" data-toggle="class:nav-off-screen" data-target="#nav"> <i class="fa fa-bars"></i> </a> <a href="<%=url_for root_path%>" class="navbar-brand" data-toggle="fullscreen">Export Tool</a> <a class="btn btn-link visible-xs" data-toggle="dropdown" data-target=".nav-user"> <i class="fa fa-cog"></i> </a> </div>
    <p id="welcomeUser">
      <%if user_signed_in?%>
       Welcome <%= current_user.email%>&nbsp &nbsp <%=link_to "Logout ", destroy_user_session_path %>
      <%end%>
    <p>
  </header>
  <section>
    <section class="hbox stretch"> <!-- .aside -->
      <aside class="bg-light lter b-r aside-md hidden-print" id="nav">
        <section class="vbox">      
          <section class="w-f scrollable">
            <div class="slim-scroll" data-height="auto" data-disable-fade-out="true" data-distance="0" data-size="5px" data-color="#333333"> <!-- nav -->
              <nav class="nav-primary hidden-xs">
                <ul class="nav">
                  <li class="active"> <a href="<%=url_for projects_path%>" > <i class="fa fa-dashboard icon"> <b class="bg-primary"></b> </i> <span>Dashboard</span> </a> </li>
                  <li> <a href="<%=url_for new_project_path%>" > <i class="fa fa-plus icon"> <b class="bg-danger"></b> </i> <span>Create Project</span> </a> </li>
                </ul>
              </nav>
              <!-- / nav --> </div>
          </section>
          <footer class="footer lt hidden-xs b-t b-light">

            <a href="#nav" data-toggle="class:nav-xs" class="pull-right btn btn-sm btn-default btn-icon"> <i class="fa fa-angle-left text"></i> <i class="fa fa-angle-right text-active"></i> </a>
          </footer>
        </section>
      </aside>
      <!-- /.aside -->
      <section id="content">
        <section class="vbox">
          <section class="scrollable padder">
            <ul class="breadcrumb no-border no-radius b-b b-light pull-in">
              <li><i class="fa fa-home"></i> Home</li>
              <li><%=(params[:controller]=='projects' && params[:action]=='index') ? 'Dashboard' : 'Project' %></li>
            </ul>
            <div class="m-b-md">
              <h3 class="m-b-none"><%=(params[:controller]=='projects' && params[:action]=='index') ? 'Dashboard' : 'Project' %></h3>
            </div>
              <%=yield%>            
          </section>
        </section>
        <a href="#" class="hide nav-off-screen-block" data-toggle="class:nav-off-screen" data-target="#nav"></a> </section>
    </section>
  </section>
</section>
<%= javascript_include_tag "application" %></body>
</html>